### ISSUE TITLE
crash due to race of multiple connections between same peers

### ISSUE THREAD

**Issue by rade** [zettio/weave#352]
Steps to reproduce:

````
A# weave launch
A# iptables -I FORWARD -s <B-ip> -p udp -j DROP
B# weave launch <A-ip>
A# weave connect <B-ip>
````

This crashes A's weave as follows:

````
weave 2015/01/16 20:11:26.950097 ->[192.168.48.15:40837] connection accepted
weave 2015/01/16 20:11:26.951556 ->[192.168.48.15:40837] completed handshake with 7a:7c:e6:2a:83:2f
weave 2015/01/16 20:11:26.951894 ->[7a:7c:e6:2a:83:2f]: connection added
weave 2015/01/16 20:11:36.826580 ->[192.168.48.15:6783] attempting connection
weave 2015/01/16 20:11:36.828516 ->[192.168.48.15:6783] completed handshake with 7a:7c:e6:2a:83:2f
weave 2015/01/16 20:11:36.829182 ->[7a:7c:e6:2a:83:2f]: connection shutting down due to error: Multiple connections to 7a:7c:e6:2a:83:2f added to 7a:2f:03:51:3d:9f
weave 2015/01/16 20:11:36.830209 ->[7a:7c:e6:2a:83:2f]: connection fully established
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x4da3aa]

goroutine 34 [running]:
github.com/zettio/weave/router.(*RawUDPSender).Send(0xc209294bd0, 0xc2092e0000, 0xea82, 0x10000, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/udp_sender.go:50 +0xba
github.com/zettio/weave/router.(*Forwarder).flush(0xc20910e980)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:306 +0xbd
github.com/zettio/weave/router.(*Forwarder).Run(0xc20910e980)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:266 +0x5be
created by github.com/zettio/weave/router.(*LocalConnection).ensureForwarders
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:54 +0x5ee
````

There's a 50/50 chance of the crash, depending on how which connection wins the tie break.

Here's what is happening...

1. A accepts connection from B and the two complete the handshake and add the connections to their connection map.
2. B starts sending fast heartbeats, but for some reason they get either delayed or dropped (in the example I used iptables to drop them).
3. A connects to B and the two complete the handshake.
4. A starts sending fast heartbeats
5. A and B shut down the 2nd connection because its a duplicate and lost the tie break.
6. B receives the heartbeat from step 4, and passes it to the actor for the current connection to A, which is the actor for the 1st connection. Since this is the first heartbeat received, it sends a `ConnectionEstablished` to A.
8. A receives the `ConnectionEstablished` on the 1st connection. It enables the udp forwarders. But it hasn't received a heartbeat yet so doesn't know the remote address. Cue crash as soon as anything gets sent by those forwarders.

This race was introduced in #349. Prior to that, in step 6, B would not have sent a `ConnectionEstablished` since it is the initiating peer and `ConnectionEstablished` was only travelling in the other direction prior to that PR. (Changing that was the point of the PR).

**Comment by rade** [comment]
So what can be done about this?

We could get A to defer processing of the `ConnectionEstablished` until it receives a heartbeat. The drawback is that when that heartbeat does finally arrive and A marks the connection as established, this is based on an invalid test, i.e. udp packets sent by A on the duplicate (and, moreover, outbound) connection, not to the new udp address it just received.

Note that this heartbeat mis-attribution could have happened prior to #349 too.

The best other approach I can think of to fix that, is to include the connection uid in the heartbeat frames. The connection actor's heartbeat handler would ignore heartbeats containing a different connection uid, so (6) above becomes a no-op.
