### ISSUE TITLE
[dns] timeout in tests

### ISSUE THREAD

**Issue by rade** [zettio/weave#363]
````
--- FAIL: TestDNSServer (2.60s)
	util.go:69: Unexpected error: read udp 127.0.0.1:17625: i/o timeout
		goroutine 74 [running]:
		github.com/zettio/weave/testing.stackTrace(0xa23700, 0x0, 0x0)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:78 +0x88
		github.com/zettio/weave/testing.StackTrace(0x0, 0x0)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:73 +0x35
		github.com/zettio/weave/testing.Fatalf(0xc20806cd80, 0x863650, 0x14, 0xc20807cde8, 0x1, 0x1)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:69 +0x27
		github.com/zettio/weave/testing.AssertNoErr(0xc20806cd80, 0x2b3254faedc0, 0xc2080a6200)
			/home/matthias/go/src/github.com/zettio/weave/testing/util.go:12 +0xea
		github.com/zettio/weave/nameserver.TestDNSServer(0xc20806cd80)
			/home/matthias/go/src/github.com/zettio/weave/nameserver/server_test.go:60 +0x967
		testing.tRunner(0xc20806cd80, 0xa20338)
			/usr/local/go/src/testing/testing.go:447 +0xbf
		created by testing.RunTests
			/usr/local/go/src/testing/testing.go:555 +0xa8b
````

**Comment by rade** [comment]
Duplicate of #347.
